name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: Version to release
      test-repository:
        required: true
        type: boolean
        default: true
        description: Upload to Test PyPI repository?
      test-package:
        required: true
        type: boolean
        default: true
        description: Try installing from Test PyPI repository?

jobs:
  Release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Set version
        run: echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
      - name: Validate version
        run: test "${{ env.VERSION }}"

      - name: Override version in setup.py
        shell: python
        run: |-
          FILE = "setup.py"
          with open(FILE, "r") as f:
            data = f.read()

          data = data.replace("$VERSION$", "${{ github.event.inputs.version }}")
          with open(FILE, "w") as f:
            f.write(data)

      - name: Override requirements in setup.py
        shell: python
        run: |-
          requirements = list()
          with open("requirements.txt", "r") as f:
            for line in f.readlines():
              line = line.split("#")[0].strip()
              if line:
                requirements.append(line)

          FILE = "setup.py"
          with open(FILE, "r") as f:
            data = f.read()

          import json
          data = data.replace("$REQUIREMENTS$", json.dumps(requirements))
          with open(FILE, "w") as f:
            f.write(data)

      - name: Set PyPI repository/token (production)
        if: ${{ github.event.inputs.test-repository == 'false' }}
        run: |-
          echo "PYPI_REPOSITORY=https://upload.pypi.org/legacy/" >> $GITHUB_ENV
          echo "PYPI_TOKEN=${{ secrets.PYPI_TOKEN }}" >> $GITHUB_ENV

      - name: Set PyPI repository/token (test)
        if: ${{ github.event.inputs.test-repository == 'true' }}
        run: |-
          echo "PYPI_REPOSITORY=https://test.pypi.org/legacy/" >> $GITHUB_ENV
          echo "PYPI_TOKEN=${{ secrets.PYPI_TEST_TOKEN }}" >> $GITHUB_ENV

      - name: Build package
        run: python setup.py sdist

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@5fb2f047e26679d7846a8370de1642ff160b9025
        with:
          repository_url: ${{ env.PYPI_REPOSITORY }}
          password: ${{ env.PYPI_TOKEN }}

  TestRelease:
    name: Test Release
    if: ${{ github.event.inputs.test-repository == 'true' && github.event.inputs.test-package == 'true' }}
    runs-on: ubuntu-latest
    needs:
      - Release

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install pnytter requirements from main PyPI repository
        run: pip install -r requirements.txt

      # TODO allow testing from production index
      - name: Install pnytter package
        uses: nick-fields/retry@v2
        with:
          timeout_seconds: 30
          max_attempts: 12
          retry_wait_seconds: 5
          retry_on: error
          command: pip install --index-url="https://test.pypi.org/simple/" "pnytter==${{ github.event.inputs.version }}"
      - name: Test
        shell: python
        run: |-
          from qqddm import AnimeConverter
          print(AnimeConverter())
